### ISSUE TITLE
Install USAboundariesData

### ISSUE THREAD

**Issue by jaeyk** [ropensci/USAboundariesData#4]
First of all, thanks for the really helpful pkg!

1. Problem 

I tried to produce `historical_us` object using `us_counties("some date in 1981")`. Then, I was asked to install the datasets (selected `1`) but the requested task was not performed. The suggested solution was `install.packages("USAboundariesData", repos = "http://packages.ropensci.org", type = "source")`.

2. Expectation 
Successful installation of the pkg from the source. 

3. I was able to install the pkg using devtools: `devtools::install_github("ropensci/USAboundariesData")`. 

4. Here's my session info:

```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
```

I suggest changing the wordings of the error message to include installing from the git repo.

**Comment by mthomas-ketchbrook** [comment]
Second @jaeyk 's comments... same issue on Windows with following setup:

R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Comment by lmullen** [comment]
This seems to work fine now. It was probably a blip with rOpenSci's CRAN-like repository. Please reopen if it is not working for you.
