### ISSUE TITLE
RDA objects have stale crs representations

### ISSUE THREAD

**Issue by rsbivand** [ropensci/USAboundariesData#5]
See https://github.com/r-spatial/sf/issues/1758; users are confused by the stale objects,

**Comment by rsbivand** [comment]
Ping - any progress?

**Comment by martinamorris** [comment]
And another ping from the user that posted the original issue on the sf repo.  Thx!

**Comment by cboettig** [comment]
@lmullen may be unavailable at the moment?  



If I understand correctly, I think the objects could be updated merely by re-running the data-raw scripts against a newer version of `sf`?e.g. running https://github.com/ropensci/USAboundariesData/blob/master/data-raw/census-shapefiles.R  etc and submitting a PR.  It's possible more recent census data are available (i.e. I see what look like newer entries in http://www2.census.gov/geo/tiger) so it might be wise to update those at the same time?  

I'm not a maintainer of the package nor familiar with the census spatial data, but can take a stab at this if we have no other takers.

**Comment by lmullen** [comment]
Fixed by #6. 

I will update and release new versions of this package and the main USAboundaries package shortly. In the meantime, you can get the updated version by installing from GitHub.

**Comment by martinamorris** [comment]
Thanks for the update, and for the packages :)
